# Site Settings
locale                   : "en-US"
title                    : "Brinda Nishith Sevak"
title_separator          : "-"
name                     : &name "Brinda Nishith Sevak"
description              : &description "PhD Candidate in Biomedical Engineering at UC Davis. Researching visual attention and working memory through electrical microstimulation of the frontal cortex ."
url                      : https://brinda3093.github.io
baseurl                  : ""
repository               : "brinda3093/brinda3093.github.io"
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               :
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
  staticman:
    allowedFields        : ['name', 'email', 'url', 'message']
    branch               : "gh-pages"
    commitMessage        : "New comment."
    filename             : comment-{@timestamp}
    format               : "yml"
    moderation           : true
    path                 : "_data/comments/{options.slug}"
    requiredFields       : ['name', 'email', 'message']
    transforms:
      email              : "md5"
    generatedFields:
      date:
        type             : "date"
        options:
          format         : "iso8601"

atom_feed:
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter  # ADD YOUR TWITTER HANDLE HERE (without @)
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :
social:
  type                   :
  name                   :
  links                  :

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          :

# Site Author
author:
  name                   : "Brinda Sevak"
  avatar                 : "profile.png"
  bio                    : "PhD Candidate | Cognitive Neuroscience & Neurotech | UC Davis"
  location               : "Davis, California"
  employer               :
  pubmed                 :
  googlescholar          : "https://scholar.google.com/citations?user=-Zj0WLEAAAAJ&hl=en&authuser=1"
  email                  : "bsevak@ucdavis.edu"
  researchgate           :
  uri                    :
  bitbucket              :
  codepen                :
  dribbble               :
  flickr                 :
  facebook               :
  foursquare             :
  github                 : "brinda3093"
  google_plus            :
  keybase                :
  instagram              :
  impactstory            :
  lastfm                 :
  linkedin               : "https://www.linkedin.com/in/brindasevak/"
  orcid                  :
  pinterest              :
  soundcloud             :
  stackoverflow          :
  steam                  :
  tumblr                 :
  twitter                : "brindasevak"
  vine                   :
  weibo                  :
  xing                   :
  youtube                :
  wikipedia              :
